version: "3.3"
services:
  mysql:
      build: .
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: P@ssw0rd
      volumes:
      - mysql_data:/var/lib/mysql
      ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
